export const menu = [
    {
        id: 1,
        listItems: [
            {
                id: 0,
                icon: "Back_Button.svg",

                url: "/",

            },
            {
                id: 1,
                title: "Homepage",
                url: "/",
                icon: "Home.svg",
            },
            {
                id: 2,
                title: "Profile",
                icon: "Accounts.svg",
            },
            {
                id: 3,
                title: "Users",
                icon: "order.svg",
            },

        ],
    }
];





export const chartBoxProduct = {
    color: "skyblue",
    icon: "/productIcon.svg",
    title: "Total Products",
    number: "238",
    dataKey: "products",
    percentage: 21,
    chartData: [
        { name: "Sun", products: 400 },
        { name: "Mon", products: 600 },
        { name: "Tue", products: 500 },
        { name: "Wed", products: 700 },
        { name: "Thu", products: 400 },
        { name: "Fri", products: 500 },
        { name: "Sat", products: 450 },
    ],
};
export const chartBoxRevenue = {
    color: "teal",
    icon: "/revenueIcon.svg",
    title: "Total Revenue",
    number: "$56.432",
    dataKey: "revenue",
    percentage: -12,
    chartData: [
        { name: "Sun", revenue: 400 },
        { name: "Mon", revenue: 600 },
        { name: "Tue", revenue: 500 },
        { name: "Wed", revenue: 700 },
        { name: "Thu", revenue: 400 },
        { name: "Fri", revenue: 500 },
        { name: "Sat", revenue: 450 },
    ],
};
export const chartBoxConversion = {
    color: "gold",
    icon: "/conversionIcon.svg",
    title: "Total Ratio",
    number: "2.6",
    dataKey: "ratio",
    percentage: 12,
    chartData: [
        { name: "Sun", ratio: 400 },
        { name: "Mon", ratio: 600 },
        { name: "Tue", ratio: 500 },
        { name: "Wed", ratio: 700 },
        { name: "Thu", ratio: 400 },
        { name: "Fri", ratio: 500 },
        { name: "Sat", ratio: 450 },
    ],
};


export const userRows = [
    {
        id: 1,
        img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        Name: "Eula",
        Rate: "5",
        "Margin Percent": "25%",
        Impressions: "1000",
        type: "Gorialla",
        Budget: "$5000",
        Revenue: "$3000",
        CTR: "5%",
        Margin: "$2000",
    },
    {
        id: 2,
        img: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=1600",
        Name: "Stella",
        Rate: "4.5",
        "Margin Percent": "20%",
        Impressions: "1200",
        type: "Gorialla",
        Budget: "$5500",
        Revenue: "$3500",
        CTR: "6%",
        Margin: "$2000",
    },
    {
        id: 3,
        img: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=1600",
        Name: "Mary",
        Rate: "4",
        "Margin Percent": "18%",
        Impressions: "900",
        type: "Gorialla",
        Budget: "$4800",
        Revenue: "$2800",
        CTR: "4%",
        Margin: "$2000",
    },
    {
        id: 4,
        img: "https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&w=1600",
        Name: "Mildred",
        Rate: "4.2",
        "Margin Percent": "22%",
        Impressions: "1100",
        type: "Gorialla",
        Budget: "$5200",
        Revenue: "$3200",
        CTR: "5.5%",
        Margin: "$2000",
    },
    {
        id: 5,
        img: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&w=1600",
        Name: "Jose",
        Rate: "4.8",
        "Margin Percent": "24%",
        Impressions: "1300",
        type: "Gorialla",
        Budget: "$5800",
        Revenue: "$3800",
        CTR: "7%",
        Margin: "$2000",
    },
    {
        id: 6,
        img: "https://images.pexels.com/photos/769745/pexels-photo-769745.jpeg?auto=compress&cs=tinysrgb&w=1600",
        Name: "Jeremy",
        Rate: "4.3",
        "Margin Percent": "21.5%",
        Impressions: "1150",
        type: "Gorialla",
        Budget: "$5300",
        Revenue: "$3300",
        CTR: "6.5%",
        Margin: "$2000",
    },
    {
        id: 7,
        img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",
        Name: "Christina",
        Rate: "4.6",
        "Margin Percent": "23%",
        Impressions: "1250",
        type: "Gorialla",
        Budget: "$5600",
        Revenue: "$3600",
        CTR: "6.5%",
        Margin: "$2000",
    },
    {
        id: 8,
        img: "https://images.pexels.com/photos/428364/pexels-photo-428364.jpeg?auto=compress&cs=tinysrgb&w=1600",
        Name: "Garrett",
        Rate: "4.4",
        "Margin Percent": "22%",
        Impressions: "1180",
        type: "Gorialla",
        Budget: "$5400",
        Revenue: "$3400",
        CTR: "6%",
        Margin: "$2000",
    },
    {
        id: 9,
        img: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
        Name: "Leah",
        Rate: "4.7",
        "Margin Percent": "23.5%",
        Impressions: "1270",
        type: "Gorialla",
        Budget: "$5700",
        Revenue: "$3700",
        CTR: "7.2%",
        Margin: "$2000",
    },
    {
        id: 10,
        img: "https://images.pexels.com/photos/775358/pexels-photo-775358.jpeg?auto=compress&cs=tinysrgb&w=1600",
        Name: "Elnora",
        Rate: "4.9",
        "Margin Percent": "25%",
        Impressions: "1350",
        type: "Gorialla",
        Budget: "$6000",
        Revenue: "$4000",
        CTR: "7.5%",
        Margin: "$2000",
    },
];


